version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis 